### ISSUE TITLE
Too large memory usage in last version

### ISSUE THREAD

**Issue by asmyasnikov** [consbio/mbtileserver#103]
Hi!
I'm use cgroups memory limitations from docker-compose.yml
```
  mbtiles:
    image: mbtiles
    environment:
      - TILE_DIR=/external,/internal
      - PORT=80
    networks:
      phoenix:
        ipv4_address: 172.18.0.21
    read_only: True
    restart: always
    volumes: ['/opt/mbtiles/:/internal', '/opt/usb/mbtiles/:/external']
    logging:
      driver: "none"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 30M
```
Limit 30M not exceed in older version. But last version (https://github.com/consbio/mbtileserver/commit/ca4a94e0c5a4487c64d271e6d1428a6aefcd094c) want about 1G of memory without limitation  =(
This is a critical for single-board computers...
Log:
```
mbtiles_1               | time="2020-05-20T15:45:59Z" level=info msg="Searching for tilesets in /external\n"
mbtiles_1               | time="2020-05-20T15:45:59Z" level=info msg="Searching for tilesets in /internal\n"
mbtiles_1               | time="2020-05-20T15:46:01Z" level=info msg="Searching for tilesets in /external\n"
mbtiles_1               | time="2020-05-20T15:46:01Z" level=info msg="Searching for tilesets in /internal\n"
docker_mbtiles_1 exited with code 137
mbtiles_1               | time="2020-05-20T15:46:04Z" level=info msg="Searching for tilesets in /external\n"
mbtiles_1               | time="2020-05-20T15:46:04Z" level=info msg="Searching for tilesets in /internal\n"
```
internal and external paths contains big mbtiles files:
```
root@debian:/etc/docker# du -sh /opt/mbtiles/*
9,2M    /opt/mbtiles/countries-raster.mbtiles
18G     /opt/mbtiles/world_yandex.mbtiles
root@debian:/etc/docker# du -sh /opt/usb/mbtiles/*
52G     /opt/usb/mbtiles/osm-2017-07-03-v3.6.1-planet.mbtiles
```
